theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
completion-trigger-len = 1
bufferline = "multiple"
color-modes = true
scroll-lines = 5

[editor.soft-wrap]
enable = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-l = [":toggle lsp.display-inlay-hints"]
J = ["extend_to_line_bounds", "delete_selection", "paste_after"]
K = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
C-b = [":sh cargo b"]
C-r = [":sh cargo r"]

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
display-inlay-hints = true
display-signature-help-docs = false
display-messages = true

[keys.insert]
C-s = ["normal_mode" , ":w"]

